### ISSUE TITLE
Hide/Show not available on password reset screen

### ISSUE THREAD

**Issue by psychodd** [barryceelen/wp-hide-show-password#1]
The hide/show does not work on the lost password screen.

![screen shot 2017-01-31 at 10 46 38 pm](https://cloud.githubusercontent.com/assets/25474821/22497635/ed5608ea-e807-11e6-9684-79c2d0e1de6d.png)

**Comment by barryceelen** [comment]
@psychodd Thanks for reporting this. As far as I can tell, this is an issue for versions of WordPress  older than 4.3. From WordPress 4.3, the 'New password’ field's content is always visible.

**Comment by psychodd** [comment]
I have version WordPress 4.7.2, and still experiencing the problem. Suggestions?

**Comment by barryceelen** [comment]
On 4.7.2, I’m getting this form with a password hint and visible text input when requesting a password reset:

![pasted_image_06_02_17_16_09](https://cloud.githubusercontent.com/assets/4179791/22652452/cd10556c-ec86-11e6-9059-5e3fc33e4494.jpg)
