### ISSUE TITLE
Feature request: optionally apply to register / reset / all password inputs

### ISSUE THREAD

**Issue by fippy** [barryceelen/wp-hide-show-password#5]
@barryceelen - I'm not sure this is the place to put this so please forgive me if incorrect.

I would really like the option to show/hide passwords on the registration pages and reset password screen (in fact anywhere I have an input of type password).

I’ve looked at your code, but I’m struggling to understand exactly how/when this functionality gets attached to an input. Can you perhaps point me in the right direction?

I've emailed you about this too. Any help appreciated!

**Comment by barryceelen** [comment]
Hi @fippy ,

this merge request illustrates how the plugin is hooked into a password field:

https://github.com/barryceelen/wp-hide-show-password/pull/3/files
